### ISSUE TITLE
 อยากเพิ่ม TAG ครับ

### ISSUE THREAD

**Issue by Bancherd-DeLong** [PyThaiNLP/thai-named-entity-recognition-data#1]
โทษทีครับ ทิ้งไปนาน ตอนนี้ผมเริ่มว่างแล้ว ผมอยากทราบวิธืเพิ่ม TAG เช่นชื่ออาหาร ไม่ทราบว่าต้องทำอย่างไรครับ?

บรรเจิด

**Comment by wannaphong** [comment]
เลือกข้อความบรรทัดละประโยคครับ เช่น
```
วันนี้เราไปที่ไหนกัน
วันที่ 13 ตุลาคม 2561 จะมีอะไรเกิดขึ้น
```
เสร็จแล้วทำการ tag ในเว็บ https://thainlp-203815.appspot.com/add.html แล้ว ส่งมา
ถ้าอยากเพิ่ม tag อื่น เช่น อาหาร ตัวอย่าง
```
ผมชอบกินข้าวผัด
คนไทยชอบกินมาม่า
```
ทำการเพิ่ม tag เอง เช่น
```
ผมชอบกิน[FOOD]ข้าวผัด[/FOOD]
คนไทยชอบกิน[FOOD]มาม่า[/FOOD]
```
ครับ
